#test_tuner: test_tuner.cpp
#	g++-11 -O3 -march=native -Wall -std=c++17 -fopenmp test_tuner.cpp -o test_tuner

# test_tuner_simpler: test_tuner_simpler.cpp
# 	g++-11 -O3 -march=native -Wall -std=c++20 -fopenmp test_tuner_simpler.cpp -o test_tuner_simpler

integer_seq: integer_seq.cpp
	g++-11 -O3 -march=native -Wall -std=c++20 -fopenmp integer_seq.cpp -o integer_seq
